---
title: "Alamar Blue Calculations"
output: html_notebook
---

```{r}
library(readxl)
library(matrixStats)
library(ggplot2)
library(reshape)

setwd("~/Google Drive File Stream/My Drive/Prabin Majhi/Experiments/PDM_3018_MEF_Cytotoxicity_RAD52-Inhibitor/3018.1_Data/")

percent_reduced <- function(filename, 
                    test_row= LETTERS[1:7], 
                    test_col= 1:12,
                    control_row= "H", 
                    control_col= 1:8,
                    blank_row= "H",
                    blank_col= 9:12){
        #load the required matrix first
                Abs <- read_excel(filename, col_names = F)
                Abs <-Abs[,-1]
                Abs_570 <- Abs[which(Abs$..14 == 570),]
                Abs_600 <- Abs[which(Abs$..14 == 600),]
                Abs_570 <- as.data.frame(Abs_570)
                colnames(Abs_570) <- seq(1:ncol(Abs_570))
                rownames(Abs_570) <- LETTERS[1:nrow(Abs_570)]
                Abs_600 <- as.data.frame(Abs_600)
                colnames(Abs_600) <- seq(1:ncol(Abs_600))
                rownames(Abs_600) <- LETTERS[1:nrow(Abs_600)]
                control_570 <- rowMeans(Abs_570[control_row, control_col]) *  14652
                control_600 <- rowMeans(Abs_600[control_row, control_col]) *   155677
                denominator <- control_600 - control_570
                test_570 <- Abs_570[test_row,]*117215
                test_600 <- Abs_600[test_row,]*80586
                nominator <- test_570 - test_600
                perc_red <- (nominator/denominator)*100
                perc_red_mean <- colMeans(perc_red)
                perc_red_se <-colSds(as.matrix(perc_red))/sqrt(nrow(perc_red))
                perc_red_out <- data.frame(mean = perc_red_mean,
                           se = perc_red_se)
                perc_red_out <- perc_red_out[1:12,]
                return(perc_red_out)
                
}

growth_datapoints <- function(
        filenames,
        celltype,
        treatment
){
        data <- lapply(filenames, function(x)percent_reduced(filename = x))
        Celltype <- rep(celltype, each = 4)
        Treatment <- rep(treatment, 3)
        data2 <- lapply(data, function(x)data.frame(x, Celltype = Celltype, Treatment = Treatment))
        data3 <- lapply(1:length(data2), function(x)data.frame(data2[[x]], day = x ))
        data4 <- do.call("rbind", data3)
        data4$Celltype <- factor(data4$Celltype, levels = unique(data4$Celltype))

        data4$Treatment <- factor(data4$Treatment, levels = unique(data4$Treatment))
        return(data4)
}

```


```{r}
setwd("~/Google Drive File Stream/My Drive/Prabin Majhi/Experiments/PDM_3018_MEF_Cytotoxicity_RAD52-Inhibitor/3018.1_Data/")
k5_h4 <- list.files(pattern = "5k-4h.xlsx")
celltype <- c("C57BL/6-Trp53+/-", "BALB/c-Trp53+/-", "SM1-Trp53+/-")
treatment = c("Ctrl", "MMC", "EGC", "MMC+EGC")


k5_data <- lapply(k5_h4, function(x)percent_reduced(filename = x))
celltype <- rep(c("C57BL/6-Trp53+/-", "BALB/c-Trp53+/-", "SM1-Trp53+/-"), each = 4)
treatment <- rep(c("Ctrl", "MMC", "EGC", "MMC+EGC"), 3)
k5_data2 <- lapply(k5_data, function(x)data.frame(x, celltype = celltype, treatment = treatment))
k5_data3 <- lapply(1:length(k5_data2), function(x)data.frame(k5_data2[[x]], day = x ))
k5_data4 <- do.call("rbind", k5_data3)
k5_data4$celltype <- factor(k5_data4$celltype, levels = unique(k5_data4$celltype))

k5_data4$treatment <- factor(k5_data4$treatment, levels = unique(k5_data4$treatment))

p <- ggplot(data = k5_data4, aes(x = day, y = mean, color = treatment)) + geom_path()
p <- p + facet_wrap(~ celltype)
print(p)

k10_h24 <- list.files(pattern = "10k-2")
k10_h24 <- k10_h24[c(1,3,5,7)]
k10_h24_data <- growth_datapoints(filenames = k10_h24,celltype = celltype, treatment = treatment)

p <- ggplot(data = k10_h24_data, aes(x = day, y = mean, color = Treatment)) + geom_line()
p <- p + facet_wrap(~ Celltype)
print(p)
```


